<?xml version="1.0" encoding="utf-8"?>

<Database Name="WorkShop" Class="ToDoDiagramDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=WorkShop;Integrated Security=True"
              SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="WorkShopConnectionString"
              Provider="System.Data.SqlClient" />
  <Table Name="WorkShop.ToDo" Member="ToDos">
    <Type Name="ToDo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContractId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ToDo_TaskChecklist" Member="TaskChecklists" ThisKey="Id" OtherKey="ToDoId"
                   Type="TaskChecklist" />
    </Type>
  </Table>
  <Table Name="WorkShop.TaskChecklist" Member="TaskChecklists">
    <Type Name="TaskChecklist">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TagId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ToDoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="TaskChecklist_AssignedTask" Member="AssignedTasks" ThisKey="Id" OtherKey="TaskChecklistId"
                   Type="AssignedTask" />
      <Association Name="ToDo_TaskChecklist" Member="ToDo" ThisKey="ToDoId" OtherKey="Id" Type="ToDo"
                   IsForeignKey="true" />
      <Association Name="Tag_TaskChecklist" Member="Tag" ThisKey="TagId" OtherKey="Name" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="WorkShop.Tag" Member="Tags">
    <Type Name="Tag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tag_TaskChecklist" Member="TaskChecklists" ThisKey="Name" OtherKey="TagId"
                   Type="TaskChecklist" />
    </Type>
  </Table>
  <Table Name="WorkShop.AssignedTask" Member="AssignedTasks">
    <Type Name="AssignedTask">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Percent]" Member="Percent" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Point" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TaskChecklistId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TaskChecklist_AssignedTask" Member="TaskChecklist" ThisKey="TaskChecklistId" OtherKey="Id"
                   Type="TaskChecklist" IsForeignKey="true" />
    </Type>
  </Table>
</Database>